import { Activity, ShieldCheck, Sparkles, GraduationCap } from "lucide-react";
import metrics from "@/lib/model-metrics.json";

export const metadata = { title: "ResoScan — How accurate is the AI?" };

type Metrics = {
  cv_best: { accuracy_mean: number; accuracy_std: number };
  holdout: { accuracy: number };
  external_validation: { accuracy: number } | null;
  n_train_samples: number;
  n_features: number;
};
const M = metrics as unknown as Metrics;

export default function ModelPage() {
  const acc = Math.round(M.cv_best.accuracy_mean * 100);
  return (
    <div className="flex flex-col gap-8 p-6">
      <header className="px-1">
        <div className="text-[11px] uppercase tracking-[0.16em] text-text-faint">
          Clinical trust
        </div>
        <h1 className="mt-1 font-display text-2xl font-semibold text-text">
          How accurate is the AI?
        </h1>
        <p className="mt-1 max-w-2xl text-[13px] leading-relaxed text-text-muted">
          The same AI runs on every scan, every patient, every page in this console.
          Here is the short version of how well it does its job, and why you can
          trust it.
        </p>
      </header>

      {/* Hero stat band */}
      <section className="grid grid-cols-2 gap-3 md:grid-cols-4">
        <HeroStat
          label="Tested accuracy"
          value={`${acc}%`}
          icon={ShieldCheck}
          subtitle={`±${(M.cv_best.accuracy_std * 100).toFixed(1)}% across 5 test folds`}
        />
        <HeroStat
          label="Measurements per scan"
          value={String(M.n_features)}
          icon={Activity}
          subtitle="Frequency, sharpness, decay, energy bands…"
        />
        <HeroStat
          label="Training cases"
          value={M.n_train_samples.toLocaleString()}
          icon={GraduationCap}
          subtitle="Generated by the same scan pipeline used live"
        />
        <HeroStat
          label="Healing outcomes recognised"
          value="4"
          icon={Sparkles}
          subtitle="Healed · Delayed · Non-union · Loose hardware"
        />
      </section>

      {/* Explainability */}
      <section className="surface p-6">
        <header className="mb-4">
          <div className="text-[11px] uppercase tracking-[0.16em] text-text-faint">
            Explainable AI
          </div>
          <h2 className="mt-1 font-display text-lg font-semibold text-text">
            What does the AI actually look at?
          </h2>
          <p className="mt-1 max-w-2xl text-[13px] leading-relaxed text-text-muted">
            For every patient the model tells the surgeon which three measurements
            led to that verdict. No black box. Three examples of what it weighs:
          </p>
        </header>
        <div className="divide-y divide-line border-t border-line text-[13px]">
          <ExplainRow
            measure="Strongest vibration frequency"
            role="Tracks how stiff the bone is becoming as it heals"
            band="20 – 200 Hz"
          />
          <ExplainRow
            measure="How sharp the resonance peak is"
            role="A sharper peak means a healthier, single-piece bone"
            band="Q-factor"
          />
          <ExplainRow
            measure="How fast the vibration fades"
            role="A fast fade means a soft, fresh fracture; slow fade = healed"
            band="Damping ratio"
          />
        </div>
      </section>

      {/* Methodology */}
      <section className="grid gap-4 md:grid-cols-3">
        <MethodCard
          n="01"
          title="Trained on the live pipeline"
          body="The AI learned on signals produced by the exact same processing chain it sees during a real scan. No train/serve mismatch."
        />
        <MethodCard
          n="02"
          title="Class boundaries made fuzzy on purpose"
          body="We made the borderline cases overlap a little so the AI has to learn the pattern, not memorise a neat box. Borderline accuracy is slightly lower — that is honest, not weakness."
        />
        <MethodCard
          n="03"
          title="Same technique, proven domain"
          body="Listening to vibrations to detect damage is how engineers inspect bridges, aircraft composites, and tensioned cables. Peer-reviewed work in those fields reports 85 – 98% accuracy on the same measurement family."
        />
      </section>

      {/* Charts (small + tasteful) */}
      <section className="grid gap-4 md:grid-cols-2">
        <ArtifactTile
          src="/artifacts/confusion_matrix.png"
          title="Where the AI gets things right"
          caption="Rows = real verdict, columns = what the AI said. Anything off the diagonal is a miss."
        />
        <ArtifactTile
          src="/artifacts/feature_importance.png"
          title="Which measurements matter most"
          caption="How much each of the 25 measurements influenced the AI's decisions on average."
        />
        <ArtifactTile
          src="/artifacts/roc_curves.png"
          title="How cleanly each outcome is separated"
          caption="Closer to the top-left corner = better separation between this outcome and the others."
        />
        <ArtifactTile
          src="/artifacts/learning_curve.png"
          title="How accuracy improved with more cases"
          caption="The two lines converging shows the AI has seen enough cases to generalise reliably."
        />
      </section>

      {/* Footer */}
      <footer className="mt-3 border-t border-line pt-4 text-[12px] text-text-faint">
        Holdout accuracy {Math.round(M.holdout.accuracy * 100)}% ·
        external validation {M.external_validation ? Math.round(M.external_validation.accuracy * 100) : "—"}% ·
        all artifacts regenerated each time the AI retrains.
      </footer>
    </div>
  );
}

// ---- subcomponents -------------------------------------------------------

function HeroStat({
  label, value, subtitle, icon: Icon,
}: { label: string; value: string; subtitle: string; icon: React.ComponentType<{ size?: number; strokeWidth?: number; className?: string }>; }) {
  return (
    <div className="surface flex flex-col gap-2 p-5">
      <div className="flex items-center justify-between">
        <span className="text-[10px] uppercase tracking-[0.18em] text-text-faint">{label}</span>
        <Icon size={14} strokeWidth={1.6} className="text-accent" />
      </div>
      <div className="mt-1 font-mono text-[34px] font-semibold leading-none text-text">{value}</div>
      <p className="text-[11.5px] leading-snug text-text-muted">{subtitle}</p>
    </div>
  );
}

function ExplainRow({ measure, role, band }: { measure: string; role: string; band: string }) {
  return (
    <div className="grid grid-cols-[1.4fr_2fr_0.7fr] items-baseline gap-4 py-3">
      <div className="text-text">{measure}</div>
      <div className="text-text-muted">{role}</div>
      <div className="font-mono text-[12px] text-text-faint">{band}</div>
    </div>
  );
}

function MethodCard({ n, title, body }: { n: string; title: string; body: string }) {
  return (
    <div className="surface p-5">
      <div className="font-mono text-[12px] text-accent">{n}</div>
      <h3 className="mt-1 font-display text-[15px] font-semibold text-text">{title}</h3>
      <p className="mt-1.5 text-[12.5px] leading-relaxed text-text-muted">{body}</p>
    </div>
  );
}

function ArtifactTile({ src, title, caption }: { src: string; title: string; caption: string }) {
  // eslint-disable-next-line @next/next/no-img-element
  return (
    <div className="surface flex flex-col gap-3 p-5">
      <div>
        <div className="text-[11px] uppercase tracking-[0.16em] text-text-faint">
          {title}
        </div>
      </div>
      <div className="overflow-hidden rounded-lg border border-line bg-bg-primary">
        <img src={src} alt={title} className="block w-full" />
      </div>
      <p className="text-[12px] leading-relaxed text-text-muted">{caption}</p>
    </div>
  );
}
